export const footerNav = [
  {
    id: 'platform',
    name: '平台',
    href: '/platform/',
    items: [
      { name: '华炎魔方概览', href: '/platform/' },
      { name: '核心功能', href: '/resources/features' },
      { name: '模版应用', href: '/resources/marketplace' },
      { name: '应用集成', href: '/resources/integration' },
      { name: '低代码', href: '/resources/low-code' },
      { name: '开发人员', href: '/resources/developer' },
      { name: '报价', href: '/platform/pricing' },
    ],
  },
  {
    id: 'ai',
    name: '人工智能',
    href: '/resources/artificial-intelligence',
    items: [
      { name: 'AI 智能文档', href: '/resources/artificial-intelligence/docs' },
      { name: 'AI 协同写作', href: '/resources/artificial-intelligence/ai-word' },
      { name: 'AI 内容审核', href: '/resources/artificial-intelligence/ai-review' },
      { name: 'AI 知识库', href: '/resources/artificial-intelligence/ai-kb' },
      { name: 'AI 自动化', href: '/resources/artificial-intelligence/ai-automation' },
      { name: '智能设备', href: '/resources/features/iot' },
    ],
  },
  {
    id: 'solutions',
    name: '解决方案',
    href: '/reources/solutions',
    items: [
      { name: '客户关系管理', href: '/resources/solutions/crm' },
      { name: '项目管理', href: '/resources/solutions/project' },
      { name: '合同管理', href: '/resources/solutions/contract' },
      { name: '费控管理', href: '/resources/solutions/cost'},
      { name: '人力资源管理', href: '/resources/solutions/hr'},
      { name: '采购管理', href: '/resources/solutions/purchase'},
      { name: '生产管理', href: '/resources/solutions/pcmes' },
    ],
  },
  {
    id: 'customer-cases',
    name: '客户案例',
    href: '/reources/customer-success-stories/',
    items: [
      { name: '百事食品', href: '/resources/customer-success-stories/pepsico' },
      { name: '中国石油', href: '/resources/customer-success-stories/cnpc-media' },
      { name: '海泰地产', href: '/resources/customer-success-stories/hitime' },
      { name: '大众公用', href: '/resources/customer-success-stories/dzug' },
      { name: '广东省二院', href: '/resources/customer-success-stories/gd2h' },
      { name: '清华大学', href: '/resources/customer-success-stories/tsinghua' },
      { name: '建华建材', href: '/resources/customer-success-stories/jianhuabm' },
    ],
  },
]
